feat: добавить user и item функционал
Vahrimur/java-shareit pull request #1
Opened 2022-08-17 21:07 UTC by Vahrimur

2022-08-18 16:29 UTC, kukolev requested changes

2022-08-18 16:29 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private void checkHeaderExists(Long userId) throws AbsentHeaderException {
Валидация это бизнес-логика, место которой в сервисе. Нужно перенести в сервис.

2022-08-18 16:29 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
> +        return id++ + 1;
По моему здесь ошибка - лучше написать просто `return ++id`.

2022-08-18 16:29 UTC, kukolev commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserDto update(@RequestBody UserDto userDto, @PathVariable("userId") Long userId) throws IncorrectFieldException, SameEmailException, IncorrectObjectException {
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину. Подробнее можно почитать тут: https://www.notion.so/praktikum/Code-guide-Java-d835be24c32d4265aeb4007652f40e6f#8454ceb4e0d6417d985c0418586015f1

2022-08-18 16:29 UTC, kukolev commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +    UserDto updateUser(UserDto userDto, Long userId) throws IncorrectFieldException, SameEmailException, IncorrectObjectException;
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину. Подробнее можно почитать тут: https://www.notion.so/praktikum/Code-guide-Java-d835be24c32d4265aeb4007652f40e6f#8454ceb4e0d6417d985c0418586015f1

2022-08-18 16:29 UTC, kukolev commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +    public UserDto updateUser(UserDto userDto, Long userId) throws IncorrectFieldException, SameEmailException, IncorrectObjectException {
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину. Подробнее можно почитать тут: https://www.notion.so/praktikum/Code-guide-Java-d835be24c32d4265aeb4007652f40e6f#8454ceb4e0d6417d985c0418586015f1

2022-08-18 19:50 UTC, Vahrimur commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +    public UserDto updateUser(UserDto userDto, Long userId) throws IncorrectFieldException, SameEmailException, IncorrectObjectException {
Исправила.

2022-08-19 05:48 UTC, kukolev approved these changes

2022-08-19 06:19 UTC, merged