feat: разбить на gateway и server и создать контейнеры
Vahrimur/java-shareit pull request #4
Opened 2022-10-04 13:28 UTC by Vahrimur

2022-10-05 08:19 UTC, kukolev requested changes

2022-10-05 08:19 UTC, kukolev commented on checkstyle.xml
>  	<!--	<module name="NewlineAtEndOfFile"/>-->
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-10-05 08:19 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        checkCorrectTime(bookingDto);
Бизнес-логика должна быть реализована в сервисном слое, а не в контроллере. Именно сервис инкапсулирует всю логику работы приложения и выставляет наружу методы, которые потом вызываются из контроллеров или из других сервисов.

Аналогично нужно поправить ниже.

2022-10-05 08:19 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +        checkCorrectItem(itemDto);
Бизнес-логика должна быть реализована в сервисном слое, а не в контроллере. Именно сервис инкапсулирует всю логику работы приложения и выставляет наружу методы, которые потом вызываются из контроллеров или из других сервисов.

Аналогично нужно поправить ниже.

2022-10-05 08:19 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +        checkCorrectDescription(itemRequestDto);
Бизнес-логика должна быть реализована в сервисном слое, а не в контроллере. Именно сервис инкапсулирует всю логику работы приложения и выставляет наружу методы, которые потом вызываются из контроллеров или из других сервисов.

Аналогично нужно поправить ниже.

2022-10-05 08:19 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareit/user/UserController.java
> +		checkEmailExists(userDto);
Бизнес-логика должна быть реализована в сервисном слое, а не в контроллере. Именно сервис инкапсулирует всю логику работы приложения и выставляет наружу методы, которые потом вызываются из контроллеров или из других сервисов.

Аналогично нужно поправить ниже.

2022-10-05 08:19 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareit/user/UserController.java
> +	public ResponseEntity<Object> createUser(@RequestBody @Valid UserDto userDto) throws IncorrectFieldException {
Отступы перед кодом выполнены с помощью Tab. Необходимо привести в соответствии с кодстайлом и сделать отступы пробелами.

2022-10-05 08:19 UTC, kukolev commented on pom.xml
> +				<plugin>
Отступы перед кодом выполнены с помощью Tab. Необходимо привести в соответствии с кодстайлом и сделать отступы пробелами.

2022-10-05 08:19 UTC, kukolev commented on server/pom.xml
> +		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
Отступы перед кодом выполнены с помощью Tab. Необходимо привести в соответствии с кодстайлом и сделать отступы пробелами.

2022-10-07 14:42 UTC, kukolev requested changes
Есть одно серьезное замечание - тесты были удалены. Согласно ТЗ тесты удалять не нужно. Нужно восстановить тесты и поправить, если необходимо.

2022-10-11 07:18 UTC, kukolev requested changes

2022-10-11 07:18 UTC, kukolev commented on server/pom.xml
> +        <dependency>
Не выполнено требование ТЗ: Нужно из shareId-server вынести в shareIt-gateway всю логику валидации входных данных — кроме той, которая требует работы с БД.

Сейчас в shareIt-server есть валидация входных параметров. Нужно этот код перенести в shareIt-gateway.

Таким образом:
1. Ни в одном из классов микросервиса shareIt-server не должно быть валидации входных параметров и DTO. Допускается только валидация при работе с БД.
2. Валидация входных параметров и DTO должна быть реализована только в микросервисе shareIt-gateway.
3. Файл pom.xml в shareIt-server не должен содержать никаких зависимостей на библиотеки валидации.

2022-10-11 07:18 UTC, kukolev commented on gateway/src/main/resources/application.properties
> +#logging.level.org.apache.http=DEBUG
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-10-11 09:07 UTC, Vahrimur commented on server/pom.xml
> +        <dependency>
Убрала лишнюю зависимость, добавила её во время добавления тестов в server, почему-то без этой зависимости тесты не хотели запускаться.

2022-10-11 15:55 UTC, kukolev approved these changes

2022-10-11 16:03 UTC, merged